name: 'Yet Another Find and Replace'
description: 'Replace and find patterns in files with any prefix and suffix'
inputs:
  prefix: 
    description: 'Prefix for pattern replacement'
    required: true
  suffix: 
    description: 'suffix for pattern replacement'
    required: true
  patterns:
    description: 'JSON string containing key-value pairs for pattern replacement'
    required: true
  files:
    description: 'Glob pattern for files to process'
    required: true
    default: '**/*'
runs:
  using: 'node20'
  main: 'dist/index.js'
