name: Example Pattern Replace Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  replace-patterns:
    runs-on: ubuntu-latest
    env:
      GAME_BACKEND_URL: ${{ vars.GAME_BACKEND_URL }}
    steps:
      - uses: actions/checkout@v4

      - name: Replace Patterns
        uses: ./
        with:
          prefix: "$$_"
          postfix: "_$$"
          patterns: |
            {
              "GAME_BACKEND_URL": "${{ env.GAME_BACKEND_URL }}"
            }
          files: "**/*.json"
