name: Example Pattern Replace Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  replace-patterns:
    runs-on: ubuntu-latest
    env:
      GAME_BACKEND_URL: ${{ vars.GAME_BACKEND_URL }}
    steps:
      - uses: actions/checkout@v4

      - name: Echo test file
        run: echo "This is a <first> and <last>" > test.txt

      - name: Replace Patterns
        uses: ./
        with:
          prefix: "<"
          suffix: ">"
          patterns: |
            {
              "first": "John",
              "last": "Doe"
            }
          files: "test.txt"

      - name: cat test file
        run: cat test.txt
